module Sound.Fluidsynth.Event
	( Channel
	, Key
	, Velocity
	, Duration
	, BankNum
	, PresetNum
	, SoundfontID
	, Value
	, Control
	, ClientID
	, Pitch
	, SeqEventType(..)
	, SeqEvent(..)
	, seqEventType
	, seqEventSource
	, seqEventDestination
	) where

import Sound.Fluidsynth.Internal.Event
